In [2]:
import numpy as np

In [4]:
var=np.array([1,2,3,4,5])
print("min : ",np.min(var),np.argmin(var))
print("max : ",np.max(var),np.argmax(var))
print("sqrt : ",np.sqrt(var))

min :  1 0
max :  5 4
sqrt :  [1.         1.41421356 1.73205081 2.         2.23606798]


np.argmin will give the positon of min element in the array
np.argmax will give the position of max element in the array

axis = 0 is for columns
axis = 1 is for rows

In [6]:
var1=np.array([[2,1,3],[9,5,6]])
print(np.min(var1,axis=0))

[2 1 3]


In [7]:
var1=np.array([[2,1,3],[9,5,6]])
print(np.max(var1,axis=0))

[9 5 6]


In [9]:
var1=np.array([[2,4,3],[9,0,6]])
print(np.max(var1,axis=1))

[4 9]


In [5]:
var2=np.array([1,2,3])
print(np.sin(var2))
print(np.cos(var2))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


cumsum: sum of all the elements from all previous elements to the present element

In [6]:
var2=np.array([1,2,3])
print(np.sin(var2))
print(np.cos(var2))
print(np.cumsum(var2))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]
