In [2]:
import numpy as np

In [3]:
var=np.array([1,2,3,4])
varadd=var+3
print(varadd)

[4 5 6 7]


In [4]:
var1=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
varadd=var1+var2
print(varadd)

[2 4 6 8]


In [7]:
var1=np.array([0,0,0,0])
var2=np.array([1,2,3,4])
varadd=var1-var2
print(varadd)

[-1 -2 -3 -4]


In [8]:
var1=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
varadd=np.add(var1,var2)
print(varadd)

[2 4 6 8]


In [9]:
var1=np.array([1,2,3,4])
varadd=np.add(var1,2)
print(varadd)

[3 4 5 6]


In [10]:
var1=np.array([1,2,3,4])
varadd=var1%3
print(varadd)

[1 2 0 1]


In [18]:
var1 = np.array([1,2,3,4])
varadd=np.reciprocal(var1)
print(var1)
print(varadd)

[1 2 3 4]
[1 0 0 0]


***** 2D ARRAY ******

In [12]:
var21=np.array([[1,2,3,4],[1,2,3,4]])
var22=np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print(var22)

varadd=var21+var22
print(varadd)

[[1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4]
 [1 2 3 4]]
[[2 4 6 8]
 [2 4 6 8]]


In [13]:
var21=np.array([[1,2,3,4],[1,2,3,4]])
var22=np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print(var22)

varadd=var21*var22
print(varadd)

[[1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4]
 [1 2 3 4]]
[[ 1  4  9 16]
 [ 1  4  9 16]]
