In [1]:
import numpy as np

In [2]:
x=[1,2,3,4]
y=np.array(x)
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [4]:
y=np.array([5,6,7,8])
print(y)
print(type(y))
print(y.ndim)

[5 6 7 8]
<class 'numpy.ndarray'>
1


In [7]:
l=[]

for i in range(0,5):
    k=int(input("Enter the value : "))
    l.append(k)
print(l)
print(np.array(l))
print(type(l))

Enter the value :  1
Enter the value :  2
Enter the value :  3
Enter the value :  4
Enter the value :  5


[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'list'>
