In [1]:
import numpy as np

In [2]:
x=[1,2,3,4]
y=np.array(x)
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [4]:
y=np.array([5,6,7,8])
print(y)
print(type(y))
print(y.ndim)

[5 6 7 8]
<class 'numpy.ndarray'>
1


In [7]:
l=[]

for i in range(0,5):
    k=int(input("Enter the value : "))
    l.append(k)
print(l)
print(np.array(l))
print(type(l))

Enter the value :  1
Enter the value :  2
Enter the value :  3
Enter the value :  4
Enter the value :  5


[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'list'>


In [2]:
import numpy as np
a2=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(np.array(a2))
print(a2.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [3]:
a3=np.array([1,2,3],ndmin=10)
print(np.array(a3))
print(a3.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
10
