In [1]:
import numpy as np

In [2]:
x=[1,2,3,4]
y=np.array(x)
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [4]:
y=np.array([5,6,7,8])
print(y)
print(type(y))
print(y.ndim)

[5 6 7 8]
<class 'numpy.ndarray'>
1


In [7]:
l=[]

for i in range(0,5):
    k=int(input("Enter the value : "))
    l.append(k)
print(l)
print(np.array(l))
print(type(l))

Enter the value :  1
Enter the value :  2
Enter the value :  3
Enter the value :  4
Enter the value :  5


[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'list'>


In [2]:
import numpy as np
a2=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(np.array(a2))
print(a2.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [3]:
a3=np.array([1,2,3],ndmin=10)
print(np.array(a3))
print(a3.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
10


In [5]:
import numpy as np
a1=np.zeros(5)
a2=np.zeros((5,3))
print(a1)
print(a2)
a3=np.ones(5)
a4=np.ones((3,5))
print(a3)
print(a4)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
ar=np.empty(4)
print(ar)

[4.65738430e-310 0.00000000e+000 4.65738401e-310 4.65738418e-310]


In [7]:
arn=np.arange(4)
print(arn)

[0 1 2 3]


In [8]:
arar=np.eye(3)
print(arar)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


linsspace

In [9]:
ar_lin=np.linspace(0,10,num=5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


****  Random   ***

Rand(): the function is used to generate a random value between 0 to 1 .

In [1]:
import numpy as np
var= np.random.rand(4)
print(var)

[0.90978483 0.43256317 0.22343571 0.30184525]


In [3]:
var1= np.random.rand(2,5)
print(var1)
print(var1.ndim)

[[0.97421784 0.76141822 0.36709014 0.14020997 0.75337235]
 [0.31343397 0.91529848 0.48470196 0.09864881 0.2343959 ]]
2


Randn(): the function is used to generate a random value close to zero . This may return positive or negative numbers as well.

In [4]:
var2= np.random.randn(5)
print(var2)

[ 0.23884838 -0.74373934 -1.45649587 -0.66191147 -0.88914762]


ranf(): the function for doing random sampling in numpy . It returns an array of specified shape and fills it with random floats in the half open interval[0.0,1.0).

In [5]:
var3=np.random.ranf(4)
print(var3)

[0.1397166  0.2608717  0.17247122 0.83883125]


randint(): the function is used to generate a random number between a given range

var4= np.random.randint(min,max,total_values)
var4=np.rando

In [2]:
import numpy as np
var4= np.random.randint(5,20,5)
print(var4)

[ 8 13 16 18 19]
