In [1]:
import numpy as np

In [2]:
x=[1,2,3,4]
y=np.array(x)
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [4]:
y=np.array([5,6,7,8])
print(y)
print(type(y))
print(y.ndim)

[5 6 7 8]
<class 'numpy.ndarray'>
1


In [7]:
l=[]

for i in range(0,5):
    k=int(input("Enter the value : "))
    l.append(k)
print(l)
print(np.array(l))
print(type(l))

Enter the value :  1
Enter the value :  2
Enter the value :  3
Enter the value :  4
Enter the value :  5


[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'list'>


In [2]:
import numpy as np
a2=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(np.array(a2))
print(a2.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [3]:
a3=np.array([1,2,3],ndmin=10)
print(np.array(a3))
print(a3.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
10


In [5]:
import numpy as np
a1=np.zeros(5)
a2=np.zeros((5,3))
print(a1)
print(a2)
a3=np.ones(5)
a4=np.ones((3,5))
print(a3)
print(a4)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
ar=np.empty(4)
print(ar)

[4.65738430e-310 0.00000000e+000 4.65738401e-310 4.65738418e-310]


In [7]:
arn=np.arange(4)
print(arn)

[0 1 2 3]


In [8]:
arar=np.eye(3)
print(arar)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


linsspace

In [9]:
ar_lin=np.linspace(0,10,num=5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]
