##  INDEXING

In [2]:
import numpy as np

In [3]:
var=np.array([9,8,7,6])
#             0,1,2,3
#           -4,-3,-2,-1
print(var[1])
print(var[-3])


8
8


In [5]:
var1=np.array([[9,8,7],[4,5,6]])
print(var1)
print(var1.ndim)
print()

print(var1[0,1])

[[9 8 7]
 [4 5 6]]
2

8


In [9]:
var2=np.array([[[1,2],[9,6]]])
print(var2)
print(var2.ndim)
print()
print(var2[0,1,1])

[[[1 2]
  [9 6]]]
3

6


In [10]:
var2=np.array([[[[1,2],[9,6]]]])
print(var2)
print()
print("Dimension : ",var2.ndim)
print()
print("Element- ",var2[0,0,1,1])

[[[[1 2]
   [9 6]]]]

Dimension :  4

Element-  6


## Slicing

In [11]:
import numpy as np

In [18]:
var=np.array([9,8,7,6,5,4,3])
#             0,1,2,3,4,5,6
print(var)
print()
print("2 to 5 : ",var[1:5])
print("2 to End : ",var[1:])
print("start to 5 : ",var[:5])

print("moving by jumping by 2 from start to end : ",var[::2])
print(var[1:6:2])

[9 8 7 6 5 4 3]

2 to 5 :  [8 7 6 5]
2 to End :  [8 7 6 5 4 3]
start to 5 :  [9 8 7 6 5]
moving by jumping by 2 from start to end :  [9 7 5 3]
[8 6 4]


In [20]:
var1=np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(var1)
print()

print("8 to 5 : ",var1[1,1:])
print("12 to 15: ", var1[2,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

8 to 5 :  [8 7 6 5]
12 to 15:  [12 13 14 15]


In [21]:
var1=np.array([[[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]]])
print(var1)
print()

print("8 to 5 : ",var1[0,1,1:])
print("12 to 15: ", var1[0,2,1:])

[[[ 1  2  3  4  5]
  [ 9  8  7  6  5]
  [11 12 13 14 15]]]

8 to 5 :  [8 7 6 5]
12 to 15:  [12 13 14 15]
