## Insert

In [1]:
import numpy as np

In [5]:
var=np.array([1,2,3,4])

print(var)
v= np.insert(var, 2 , 40)
print(v)
v= np.insert(var, (2,4) , 40)
print(v)
v= np.insert(var, (2,4) , 2.2)
print(v)

[1 2 3 4]
[ 1  2 40  3  4]
[ 1  2 40  3  4 40]
[1 2 2 3 4 2]


In [12]:
var1=np.array([[1,2,3],[4,5,6]])
v1=np.insert(var1, 2, 6, axis=0)
print(v1)
print()
v1=np.insert(var1, 2, 6, axis=1)
print(v1)
print()
v1=np.insert(var1, 2, [22,23,24], axis=0)
print(v1)

print()
print("Using append")
x=np.append(var,6.5)
print(x)

[[1 2 3]
 [4 5 6]
 [6 6 6]]

[[1 2 6 3]
 [4 5 6 6]]

[[ 1  2  3]
 [ 4  5  6]
 [22 23 24]]

Using append
[1.  2.  3.  4.  6.5]


In [14]:
va1=np.array([[1,2,3],[4,5,6]])
v1=np.append(va1,[[45,44,23]],axis=0)
print(v1)

[[ 1  2  3]
 [ 4  5  6]
 [45 44 23]]


## Delete

In [16]:
import numpy as np
var1=np.array([1,2,3,4])
print(var1)
d=np.delete(var1,2)
print(d)

[1 2 3 4]
[1 2 4]
