##Iteration

In [3]:
import numpy as np
var=np.array([9,8,7,6,5,4])
print(var)
print()

for i in var:
    print(i)

[9 8 7 6 5 4]

9
8
7
6
5
4


In [5]:
var1=np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()

for j in var1:
    print(j)
print()
for i in var1:
    for j in i:
        print(j)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


In [8]:
var3=np.array([[[1,2,3,4],[5,6,7,8]]])
print(var1)
print("Dimension: ",var1.ndim)
print()
for i in var3:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3 4]
  [5 6 7 8]]]
Dimension:  3

1
2
3
4
5
6
7
8


## nditer function 

In [10]:
var4=np.array([[[1,2,3,4],[5,6,7,8]]])
print(var4)
print("Dimension: ",var4.ndim)
print()

for i in np.nditer(var4):
    print(i)

[[[1 2 3 4]
  [5 6 7 8]]]
Dimension:  3

1
2
3
4
5
6
7
8


## If i want to save the iterated data and wants to change the type of data than that can be done -, flags=['buffered'],op_dtypes=["S"] S is for strings. 

In [14]:
var4=np.array([[[1,2,3,4],[5,6,7,8]]])
print(var4)
print("Dimension: ",var4.ndim)
print()

for i in np.nditer(var4,flags=['buffered'],op_dtypes=["S"]):
    print(i)   

[[[1 2 3 4]
  [5 6 7 8]]]
Dimension:  3

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'


## To get data with the index value 
## using ndenumerate()

In [15]:
var4=np.array([[[1,2,3,4],[5,6,7,8]]])
print(var4)
print("Dimension: ",var4.ndim)
print()

for i,d in np.ndenumerate(var4):
    print(i,d)   

[[[1 2 3 4]
  [5 6 7 8]]]
Dimension:  3

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8
