## Matrix

In [6]:
import numpy as np

var=np.matrix([[1,2],[1,2]])
var2=np.matrix([[1,2],[1,2]])

print(var)
print()
print(var2)
print(type(var))
print()
print(var*var2)
print()
print(var.dot(var2))

[[1 2]
 [1 2]]

[[1 2]
 [1 2]]
<class 'numpy.matrix'>

[[3 6]
 [3 6]]

[[3 6]
 [3 6]]


In [7]:
var1=np.array([[1,2,3],[1,2,3]])
print(var1)
print(type(var1))
print()
print(var1*var1)

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>

[[1 4 9]
 [1 4 9]]


## Transpose

In [10]:
import numpy as np
ar=np.matrix([[1,2,3],[4,5,6]])
print(ar)
print()
print(np.transpose(ar))
print()
print(ar.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


## Swapaxes

In [16]:
ar1=np.matrix([[1,2,3],[4,5,6]])
print(np.swapaxes(ar1,0,1))
print()

var2=np.matrix([[1,2],[3,4]])
print(var2)
print()
print(np.swapaxes(var2,0,1))

[[1 4]
 [2 5]
 [3 6]]

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


## Inverse

In [17]:
var3=np.matrix([[1,2],[3,4]])
print(var3)
print()

print(np.linalg.inv(var3))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


## Power

In [20]:
var4=np.matrix([[1,2],[3,4]])
print(var4)
print()

print(np.linalg.matrix_power(var4,2))
print()

print(np.linalg.matrix_power(var4,0))
print()

print(np.linalg.matrix_power(var4,-2))
print()

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]



## Determinate

In [25]:
var5=np.matrix([[1,2],[3,4]])
print(var5)
print()
print(np.linalg.det(var5))

print()
var5=np.matrix([[1,2,3],[3,4,3],[1,2,3]])
print(var5)
print()
print(np.linalg.det(var5))

print()
var5=np.matrix([[1,2,3],[4,45,26],[17,28,19]])
print(var5)
print()
print(np.linalg.det(var5))

[[1 2]
 [3 4]]

-2.0000000000000004

[[1 2 3]
 [3 4 3]
 [1 2 3]]

0.0

[[ 1  2  3]
 [ 4 45 26]
 [17 28 19]]

-1099.9999999999995
