## FUNCTIONS -,

## Search

In [1]:
import numpy as np

In [3]:
var=np.array([1,2,3,4,2,5,2,5,6,7])

x=np.where(var==2)
print(x)
x=np.where((var%2)==0)
print(x)

(array([1, 4, 6]),)
(array([1, 3, 4, 6, 8]),)


In [37]:
varer=np.array([1,2,3,4,6,7])

rx1=np.searchsorted(varer,5)
print(rx1)
rx2=np.searchsorted(varer, 5, side='right')
print(rx2)

4
4


## Sort

In [39]:
va_1=np.array([11,2,30,14,2,5,1,0,9,7])
print(np.sort(va_1))

[ 0  1  2  2  5  7  9 11 14 30]


In [40]:
var_2=np.array(["d","a","m","b","l"])
print(np.sort(var_2))

['a' 'b' 'd' 'l' 'm']


In [42]:
va_3=np.array([[11,2],[30,14],[2,5],[1,0],[9,7]])
print(np.sort(va_3))


[[ 2 11]
 [14 30]
 [ 2  5]
 [ 0  1]
 [ 7  9]]


## Filter

In [45]:
vvar=np.array(["a","s","d","f"])
f=[True,False,False,True]
new_a=vvar[f]
print(new_a)
print(type(new_a))

['a' 'f']
<class 'numpy.ndarray'>


## Shuffle

In [49]:
van=np.array([1,2,3,4,5])
np.random.shuffle(van)
print(van)

[3 5 4 2 1]


## Unique

In [51]:
ba=np.array([1,2,3,4,2,5,3,6,2,7])
xr=np.unique(ba)
print(xr)

[1 2 3 4 5 6 7]


In [52]:
ba=np.array([1,2,3,4,2,5,3,6,2,7])
xr=np.unique(ba,return_index=True)
print(xr)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 9]))


In [54]:
ba=np.array([1,2,3,4,2,5,3,6,2,7])
xr=np.unique(ba,return_index=True,return_counts=True)
print(xr)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 9]), array([1, 3, 2, 1, 1, 1, 1]))


## Resize

In [55]:
nb=np.array([1,2,3,4,5,6])
y=np.resize(nb,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


Order:{'C','F','A','K'}, Optional
-> 'C' means to flatten in row-major(C-style) order.
-> 'F' means to flatten in column-major(Fortran-style) order.
-> 'A' means to flatten in column-major order if 'a' is Fortran *contiguous* in memory ,row-major order otherwise.
->'K' means to flatten 'a' in the order the elements occur in memory
->The default is'C'.

## Flatten and Ravel

In [61]:
nb=np.array([1,2,3,4,5,6])
y=np.resize(nb,(3,2))
print(y)
print()

print("Flatten : ",y.flatten(order="F"))
print("Ravel : ",np.ravel(y))
print("Ravel : ",np.ravel(y,order="F"))
print("Ravel : ",np.ravel(y,order="A"))
print("Ravel : ",np.ravel(y,order="K"))

[[1 2]
 [3 4]
 [5 6]]

Flatten :  [1 3 5 2 4 6]
Ravel :  [1 2 3 4 5 6]
Ravel :  [1 3 5 2 4 6]
Ravel :  [1 2 3 4 5 6]
Ravel :  [1 2 3 4 5 6]
