##Function

##Search

In [1]:
import numpy as np

In [3]:
var=np.array([1,2,3,4,2,5,2,5,6,7])

x=np.where(var==2)
print(x)
x=np.where((var%2)==0)
print(x)

(array([1, 4, 6]),)
(array([1, 3, 4, 6, 8]),)


In [37]:
varer=np.array([1,2,3,4,6,7])

rx1=np.searchsorted(varer,5)
print(rx1)
rx2=np.searchsorted(varer, 5, side='right')
print(rx2)

4
4


## Sort

In [39]:
va_1=np.array([11,2,30,14,2,5,1,0,9,7])
print(np.sort(va_1))

[ 0  1  2  2  5  7  9 11 14 30]


In [40]:
var_2=np.array(["d","a","m","b","l"])
print(np.sort(var_2))

['a' 'b' 'd' 'l' 'm']


In [42]:
va_3=np.array([[11,2],[30,14],[2,5],[1,0],[9,7]])
print(np.sort(va_3))


[[ 2 11]
 [14 30]
 [ 2  5]
 [ 0  1]
 [ 7  9]]


## Filter

In [45]:
vvar=np.array(["a","s","d","f"])
f=[True,False,False,True]
new_a=vvar[f]
print(new_a)
print(type(new_a))

['a' 'f']
<class 'numpy.ndarray'>
