In [1]:
import numpy as np

In [4]:
var= np.array([[1,2,3,4],[1,2,5,6]])
print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 2 5 6]]

(2, 4)


In [6]:
var1=np.array([1,2,3,4],ndmin=4)
print(var1)
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


In [ ]:
# in the previous 1,1,1 represents that there are there rows and 4 columns but that why written in 1,1,1, no 3 because of 4 dimentions


In [ ]:

##*****RESHAPE *****

In [18]:
var2= np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)

print()

x= var2.reshape(3,2)

print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2
